### ISSUE TITLE
Pre conditions failing in Rectangle Implementation

### ISSUE THREAD

**Issue by krishnaram** [davidmoten/rtree#173]
We want form rectangle from below values

x1:-608127936(-5097269)(-50.97269) x2:-601075968(-5038161)(-50.38161) y1:-1279040(-10721)(-1.0721) y2:859200(7202)(0.07202)
               Lat/Long Entry:-0.10721,-50.97269 Exit:0.07202,-50.38161                    

We are getting this exception.
    

> [2023-01-29T10:10:02.386Z] Caused by: java.lang.IllegalArgumentException
> [2023-01-29T10:10:02.386Z] 	at com.github.davidmoten.guavamini.Preconditions.checkArgument(Preconditions.java:25)
> [2023-01-29T10:10:02.386Z] 	at com.github.davidmoten.rtree.geometry.RectangleImpl.<init>(RectangleImpl.java:12)
> [2023-01-29T10:10:02.386Z] 	at com.github.davidmoten.rtree.geometry.RectangleImpl.create(RectangleImpl.java:25)
> [2023-01-29T10:10:02.386Z] 	at com.github.davidmoten.rtree.geometry.Geometries.rectangle(Geometries.java:24)

**Note: All rectangle geometry passing through equator means latitude is changing from -ve to +ve is failing for us.**

**Comment by krishnaram** [comment]
@davidmoten  please help in this

**Comment by davidmoten** [comment]
Can't you tell from the Precondition? You appear to be using an old version, please try on latest, actual code useful for me please.

**Comment by pangwangshu** [comment]
I could reproduce this. The exception comes from `rectangleGeographic()`: it normalizes longitude for antimeridian wraparound but never did the equivalent for latitude, so any rectangle whose entry latitude is greater than its exit latitude (e.g. crossing the equator, like the `-0.10721` → `0.07202` example above) ends up with `y1 > y2`, which violates the `y2 >= y1` precondition and throws `IllegalArgumentException`.

Opened a fix that normalizes lat1/lat2 to min/max the same way longitude is already normalized: #291
