### ISSUE TITLE
Can't Serialize Custom Geometries

### ISSUE THREAD

**Issue by Nath5** [davidmoten/rtree#44]
Hello,

I am trying to serialize my RTree of type <CustomObject, Polygon> using the following code:

`            OutputStream os = new FileOutputStream(new File("test.tree"));
            Serializer<Fence, Polygon> serializer = Serializers.flatBuffers().javaIo();
            serializer.write(tree, os);
`

I keep getting the following error:

`
java.lang.RuntimeException: unexpected
	at com.github.davidmoten.rtree.fbs.FlatBuffersHelper.addEntries(FlatBuffersHelper.java:60)
	at com.github.davidmoten.rtree.fbs.SerializerFlatBuffers.addNode(SerializerFlatBuffers.java:96)
	at com.github.davidmoten.rtree.fbs.SerializerFlatBuffers.write(SerializerFlatBuffers.java:73)
	at CreateDataTests.main(CreateDataTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
`

It looks like the addEntries method of FlatBuffersHelper can only process the built in geometries.  Is there a way around this?

Thanks

**Comment by davidmoten** [comment]
Not at the moment, but I'll think about it. Do you have any suggestions?

**Comment by Nath5** [comment]
I will have to take a deeper look into how you are doing the serialization.  Just wanted to make sure there wasn't something simple I was missing.
