### ISSUE TITLE
400000 geographic data bring rtree error

### ISSUE THREAD

**Issue by liyihongcug** [davidmoten/rtree#59]
public class LatLongExampleTest {    (I read from a.txt)
400000 data     geographic data
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at com.github.davidmoten.rtree.internal.Util.replace(Util.java:78)
    at com.github.davidmoten.rtree.internal.NonLeafHelper.add(NonLeafHelper.java:48)
    at com.github.davidmoten.rtree.internal.NonLeafDefault.add(NonLeafDefault.java:47)
    at com.github.davidmoten.rtree.RTree.add(RTree.java:320)
    at com.github.davidmoten.rtree.RTree.add(RTree.java:346)
    at com.github.davidmoten.rtree.Utilities.entries400000(Utilities.java:59)
    at com.github.davidmoten.rtree.RTreeTest.main(RTreeTest.java:1067)

**Comment by liyihongcug** [comment]
solved.  But I think its running time is slow
2016/07/29 14:36:20.392
2016/07/29 14:36:20.591       this is my running time  (0.2 second)
Operation is search(tree, Geometries.point(121.182497,31.79968),0.005)

**Comment by davidmoten** [comment]
Does your benchmark include load time from disk? Did you run it many times in a loop so hot spot would compile crtitical code? JMH is the standard tool for benchmarking.

**Comment by davidmoten** [comment]
Can you show me your code?

**Comment by davidmoten** [comment]
closing for lack of response, feel free to reopen if you have more info.
