### ISSUE TITLE
position prediction fails for close-to-the-dateline

### ISSUE THREAD

**Issue by emilburzo** [davidmoten/rtree#87]
It appears that the position predictor has difficulties near the dateline meridian.

You can see in the output below that it's a positive value instead of a negative one.

Testcase:

```
public void test180Meridian() {
	int distanceKm = 10;
	Position from = Position.create(-16.796686666666666, -179.99983333333333);
	Position north = from.predict(distanceKm, 0);
	Position south = from.predict(distanceKm, 180);
	Position east = from.predict(distanceKm, 90);
	Position west = from.predict(distanceKm, 270);

	System.out.println(north);
	System.out.println(south);
	System.out.println(east);
	System.out.println(west);

	Geometries.rectangle(west.getLon(), south.getLat(), east.getLon(), north.getLat());
}
```

Output:

```
[-16.706754647233197,-179.99983333333333]
[-16.886618686100135,-179.99983333333333]
[-16.79666536204166,-179.90589349094225]
[-16.79666536204166,179.9062268242756]
```

Stacktrace:

```
java.lang.IllegalArgumentException
	at com.github.davidmoten.guavamini.Preconditions.checkArgument(Preconditions.java:25)
	at com.github.davidmoten.rtree.geometry.internal.RectangleDouble.<init>(RectangleDouble.java:14)
	at com.github.davidmoten.rtree.geometry.internal.RectangleDouble.create(RectangleDouble.java:23)
	at com.github.davidmoten.rtree.geometry.Geometries.rectangleDouble(Geometries.java:58)
	at com.github.davidmoten.rtree.geometry.Geometries.rectangle(Geometries.java:36)
```

**Comment by davidmoten** [comment]
I think there are some normalization offerings with other methods like `Geometries.rectangleGeographic`. You may still have to break your desired search region into two rectangles (one left of the 180 longitude line and the other right of it).

**Comment by emilburzo** [comment]
Ok, I just thought it might make sense for the position predictor to be capped at the dateline, but I admit I am not sure of the implications.

Thanks for the `Geometries.rectangleGeographic` tip!
